#
# Copyright (C) 2019 LPN Plant
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for LoRaWAN packet forwarder
LUCI_DEPENDS:=+packet-forwarder

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
